name: 刷步数

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 开始
      run: 
        /opt/hostedtoolcache/Python/3.7.11/x64/bin/python -m pip install --upgrade pip
        pip install requests
        sckey='${{ secrets.SCKEY }}'
        key='${{ secrets.KEY }}'
        corpid='${{ secrets.CORPID }}'
        corpsecret='${{ secrets.CORPSECRET }}'
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        step='${{ secrets.STEP }}'
        tgbotoken ='${{ secrets.TGBOTOKEN }}'
        chatid ='${{ secrets.CHATID }}'
        
        python3 main.py <<EOF
